### ISSUE TITLE
Errors when building wheel using pip

### ISSUE THREAD

**Issue by tjd2002** [magland/isosplit5_python#5]
If you create a clean python env (e.g. with `conda create -n install_test python pip`) and attempt to install isosplit from PyPi with pip, you get an error about being unable to import pybind11 during the process of building a wheel. If you run setup.py bdist_wheel manually against the source, then you don't get this error. However in both cases the installation seems to otherwise succeed. This is a placeholder issue to try to track down what's going on here.

```
$ pip install isosplit5
Collecting isosplit5
  Using cached https://files.pythonhosted.org/packages/9d/11/13376e6e28f2442796d1967bd9e46f9686f030f5c41403d825c5ce1a13e3/isosplit5-0.1.3.tar.gz
Collecting numpy (from isosplit5)
  Using cached https://files.pythonhosted.org/packages/bb/76/24e9f32c78e6f6fb26cf2596b428f393bf015b63459468119f282f70a7fd/numpy-1.16.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting pybind11>=2.2 (from isosplit5)
  Using cached https://files.pythonhosted.org/packages/f2/7c/e71995e59e108799800cb0fce6c4b4927914d7eada0723dd20bae3b51786/pybind11-2.2.4-py2.py3-none-any.whl
Building wheels for collected packages: isosplit5
  Building wheel for isosplit5 (setup.py) ... error
  ERROR: Complete output from command /home/tjd/conda/envs/isosplit5_pip2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-7zk7lywy/isosplit5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dj2qdj74 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/isosplit5
  copying isosplit5/__init__.py -> build/lib.linux-x86_64-3.7/isosplit5
  running build_ext
  creating tmp
  gcc -pthread -B /home/tjd/conda/envs/isosplit5_pip2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/tjd/conda/envs/isosplit5_pip2/include/python3.7m -c /tmp/tmp0m3gcq97.cpp -o tmp/tmp0m3gcq97.o -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/tjd/conda/envs/isosplit5_pip2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/tjd/conda/envs/isosplit5_pip2/include/python3.7m -c /tmp/tmp2s_jsj6x.cpp -o tmp/tmp2s_jsj6x.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  building 'isosplit5_interface' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-7zk7lywy/isosplit5/setup.py", line 102, in <module>
      'numpy','pybind11>=2.2'
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-7zk7lywy/isosplit5/setup.py", line 83, in build_extensions
      build_ext.build_extensions(self)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/ccompiler.py", line 566, in compile
      depends, extra_postargs)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/ccompiler.py", line 341, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/home/tjd/conda/envs/isosplit5_pip2/lib/python3.7/distutils/ccompiler.py", line 1075, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
    File "/tmp/pip-install-7zk7lywy/isosplit5/setup.py", line 15, in __str__
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  ----------------------------------------
  ERROR: Failed building wheel for isosplit5
  Running setup.py clean for isosplit5
Failed to build isosplit5
Installing collected packages: numpy, pybind11, isosplit5
  Running setup.py install for isosplit5 ... done
Successfully installed isosplit5-0.1.3 numpy-1.16.3 pybind11-2.2.4
```

**Comment by tjd2002** [comment]
Maybe related to: https://github.com/pybind/python_example/issues/32

**Comment by magland** [comment]
So maybe we should try: setup_requires=['pybind11>=2.2'] as that post suggests?
